#---------Exceptions------------
#x is human error This will thrown error and next print statements wont get executed
#To handle this we are using try & expect blocks
print("This is starting of the program")
print("This is starting of the program")
print("This is starting of the program")
try:
    print(x)
except:
    print("Exception occured")
print("This is end of the program")
print("This is end of the program")
print("This is end of the program")